schema: "classroom50/repo-config/v1"
classroom: "comp-7082-f26"
assignment: "activity-1-b-pair-programming"
owner:
  username: "nikitalbnv"
  id: 114199158
  accepted_at: "2026-09-12T02:54:14Z"
source:
  owner: "nabil-bcit-org"
  owner_id: 326342404
  repo: "Activity-1.b-Pair-Programming"
  branch: "main"
